version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: repo-explorer-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app # Map code từ máy thật vào container để hot-reload
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: repo-explorer-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app # Map code FE
      - /app/node_modules # Bỏ qua thư mục node_modules trong map để tránh lỗi hệ điều hành
    depends_on:
      - backend